namespace Mntone.AngelUmbrella
{
	namespace Composition.SystemBackdrops
	{

		enum DesktopAcrylicKind
		{
		    Default,
			Base,
		};

		enum DesktopAcrylicTheme
		{
		    Default,
			Light,
			Dark,
			AccentLight,
			AccentDark,
		};

		[static_name("IDesktopAcrylicHelperStatics", 1E604D41-B809-4F4D-8FF3-5E4BD2562A3D)]
		static runtimeclass DesktopAcrylicHelper
		{
			[default_overload]
			[method_name("SetColors")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				DesktopAcrylicTheme theme);

			[method_name("SetColorsWithSystemBackdropTheme")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme theme);

			[default_overload]
			[method_name("SetColorsWithKind")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				DesktopAcrylicTheme theme,
				DesktopAcrylicKind kind);

			[method_name("SetColorsWithSystemBackdropThemeAndKind")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme theme,
				DesktopAcrylicKind kind);
		};

	}

	namespace Converters
	{

		[interface_name("IBooleanToVisibilityConverter", 21B28859-FCD9-4864-AC23-22C222C33DC6)]
	    runtimeclass BooleanToVisibilityConverter : Microsoft.UI.Xaml.Data.IValueConverter
		{
		    BooleanToVisibilityConverter();
		}

		[interface_name("IInvertedBooleanConverter", 0CA51023-05A7-474E-9EC2-00E6F1AFD194)]
	    runtimeclass InvertedBooleanConverter : Microsoft.UI.Xaml.Data.IValueConverter
		{
		    InvertedBooleanConverter();
		}

		[interface_name("IStringIsPresentToVisibilityConverter", A0144BE4-B8E9-4EFC-9CE0-DC48EB2416A7)]
		runtimeclass StringIsPresentToVisibilityConverter : Microsoft.UI.Xaml.Data.IValueConverter
		{
		    StringIsPresentToVisibilityConverter();
		}

	}

	namespace Controls
	{

		[constructor_name("ISettingsCardFactory", CEA37F79-B848-562C-BC32-4046419F28A7)]
		[interface_name("ISettingsCard", A98BF3E6-1595-4879-A198-93B5F6242233)]
		[static_name("ISettingsCardStatics", 34C8763E-7086-5B2F-9117-4A2C78455171)]
		[webhosthidden]
		unsealed runtimeclass SettingsCard : Microsoft.UI.Xaml.Controls.Primitives.ButtonBase
		{
			SettingsCard();

			Microsoft.UI.Xaml.Controls.IconElement ActionIcon;
			String ActionIconTooltip;
			Object Description;
			Microsoft.UI.Xaml.Controls.IconElement HeaderIcon;
			Object Header;
			Boolean IsClickEnabled;
			Microsoft.UI.Xaml.Controls.Orientation Orientation;

			static Microsoft.UI.Xaml.DependencyProperty ActionIconProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty ActionIconTooltipProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty HeaderProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty IsClickEnabledProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty OrientationProperty { get; };
		}

		[constructor_name("ISettingsExpanderFactory", D8AE545F-BEB9-48A0-AD0F-5470C827D102)]
		[interface_name("ISettingsExpander", 4AF7A35C-93BB-4560-8813-06CD71C70CF7)]
		[static_name("ISettingsExpanderStatics", 8C6C1111-678F-4BB1-A910-6EAE3B9E471F)]
		[webhosthidden]
		unsealed runtimeclass SettingsExpander : Microsoft.UI.Xaml.Controls.Expander
		{
			SettingsExpander();

			Object Description;
			Object ExpanderContent;
			Microsoft.UI.Xaml.Controls.IconElement HeaderIcon;
			Microsoft.UI.Xaml.Controls.Orientation Orientation;

			static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty ExpanderContentProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty OrientationProperty { get; };
		}

		[constructor_name("ISettingsPanelFactory", 4899B1B1-8986-4B66-9D71-3F01886E0A09)]
		[interface_name("ISettingsPanel", D7EA45B0-9CCC-404D-9148-80088E41632F)]
		[static_name("ISettingsPanelStatics", B419CC29-7DA3-4CC4-9D13-5E1444EF5C9E)]
		[webhosthidden]
		unsealed runtimeclass SettingsPanel : Microsoft.UI.Xaml.Controls.ContentControl
		{
			SettingsPanel();

			Object Description;
			Microsoft.UI.Xaml.Controls.IconElement HeaderIcon;
			Object Header;
			Microsoft.UI.Xaml.Controls.Orientation Orientation;

			static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty HeaderProperty { get; };
			static Microsoft.UI.Xaml.DependencyProperty OrientationProperty { get; };
		}

	}
}
