namespace Mntone.AngelUmbrella
{
	namespace Composition.SystemBackdrops
	{

		enum DesktopAcrylicKind
		{
		    Default,
			Base,
		};

		enum DesktopAcrylicTheme
		{
		    Default,
			Light,
			Dark,
			AccentLight,
			AccentDark,
		};

		[static_name("IDesktopAcrylicHelperStatics", 1E604D41-B809-4F4D-8FF3-5E4BD2562A3D)]
		static runtimeclass DesktopAcrylicHelper
		{
			[default_overload]
			[method_name("SetColors")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				DesktopAcrylicTheme theme);

			[method_name("SetColorsWithSystemBackdropTheme")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme theme);

			[default_overload]
			[method_name("SetColorsWithKind")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				DesktopAcrylicTheme theme,
				DesktopAcrylicKind kind);

			[method_name("SetColorsWithSystemBackdropThemeAndKind")]
		    static void SetColors(
				Microsoft.UI.Composition.SystemBackdrops.DesktopAcrylicController controller,
				Microsoft.UI.Composition.SystemBackdrops.SystemBackdropTheme theme,
				DesktopAcrylicKind kind);
		};

	}

	namespace Converters
	{

		[interface_name("IBooleanToVisibilityConverter", 21B28859-FCD9-4864-AC23-22C222C33DC6)]
	    runtimeclass BooleanToVisibilityConverter : Microsoft.UI.Xaml.Data.IValueConverter
		{
		    BooleanToVisibilityConverter();
		}

		[interface_name("IDateTimeToStringConverter", 3EEE62D6-3584-41DC-9BE8-2911A9BB7F54)]
		runtimeclass DateTimeToStringConverter : Microsoft.UI.Xaml.Data.IValueConverter
		{
			DateTimeToStringConverter();

			[noexcept] String Format;
		}

		[interface_name("IInvertedBooleanConverter", 0CA51023-05A7-474E-9EC2-00E6F1AFD194)]
	    runtimeclass InvertedBooleanConverter : Microsoft.UI.Xaml.Data.IValueConverter
		{
		    InvertedBooleanConverter();
		}

		[interface_name("IStringIsPresentToVisibilityConverter", A0144BE4-B8E9-4EFC-9CE0-DC48EB2416A7)]
		runtimeclass StringIsPresentToVisibilityConverter : Microsoft.UI.Xaml.Data.IValueConverter
		{
		    StringIsPresentToVisibilityConverter();
		}

	}

	namespace Controls
	{

		[constructor_name("ISettingsCardFactory", CEA37F79-B848-562C-BC32-4046419F28A7)]
		[interface_name("ISettingsCard", A98BF3E6-1595-4879-A198-93B5F6242233)]
		[static_name("ISettingsCardStatics", 34C8763E-7086-5B2F-9117-4A2C78455171)]
		[webhosthidden]
		unsealed runtimeclass SettingsCard : Microsoft.UI.Xaml.Controls.Button
		{
			SettingsCard();

			Microsoft.UI.Xaml.Controls.IconElement ActionIcon;
			String ActionIconTooltip;
			Object Description;
			Microsoft.UI.Xaml.Controls.IconElement HeaderIcon;
			Object Header;
			Boolean IsClickEnabled;
			Microsoft.UI.Xaml.Controls.Orientation Orientation;

			[noexcept] static Microsoft.UI.Xaml.DependencyProperty ActionIconProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty ActionIconTooltipProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty HeaderProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty IsClickEnabledProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty OrientationProperty { get; };
		}

		[constructor_name("ISettingsExpanderFactory", D8AE545F-BEB9-48A0-AD0F-5470C827D102)]
		[interface_name("ISettingsExpander", 4AF7A35C-93BB-4560-8813-06CD71C70CF7)]
		[static_name("ISettingsExpanderStatics", 8C6C1111-678F-4BB1-A910-6EAE3B9E471F)]
		[webhosthidden]
		unsealed runtimeclass SettingsExpander : Microsoft.UI.Xaml.Controls.Expander
		{
			SettingsExpander();

			Object Description;
			Object ExpanderContent;
			Microsoft.UI.Xaml.Controls.IconElement HeaderIcon;
			Microsoft.UI.Xaml.Controls.Orientation Orientation;

			[noexcept] static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty ExpanderContentProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty OrientationProperty { get; };
		}

		[constructor_name("ISettingsPanelFactory", 4899B1B1-8986-4B66-9D71-3F01886E0A09)]
		[interface_name("ISettingsPanel", D7EA45B0-9CCC-404D-9148-80088E41632F)]
		[static_name("ISettingsPanelStatics", B419CC29-7DA3-4CC4-9D13-5E1444EF5C9E)]
		[webhosthidden]
		unsealed runtimeclass SettingsPanel : Microsoft.UI.Xaml.Controls.ContentControl
		{
			SettingsPanel();

			Object Description;
			Microsoft.UI.Xaml.Controls.IconElement HeaderIcon;
			Object Header;
			Microsoft.UI.Xaml.Controls.Orientation Orientation;

			[noexcept] static Microsoft.UI.Xaml.DependencyProperty DescriptionProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty HeaderIconProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty HeaderProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty OrientationProperty { get; };
		}

		[interface_name("IOddEvenStyleSelector", 3B317E48-32FE-4922-8812-671E697B31B1)]
		runtimeclass OddEvenStyleSelector : Microsoft.UI.Xaml.Controls.StyleSelector
		{
		    OddEvenStyleSelector();

			[noexcept] Microsoft.UI.Xaml.Style OddStyle;
			[noexcept] Microsoft.UI.Xaml.Style EvenStyle;
		}

	}

	namespace Automation.Peers
	{
		[interface_name("ISettingsCardAutomationPeer", D6653E09-9104-4C95-AA35-27970B7667EE)]
	    [webhosthidden]
		unsealed runtimeclass SettingsCardAutomationPeer : Microsoft.UI.Xaml.Automation.Peers.ButtonAutomationPeer
		{
		    SettingsCardAutomationPeer(Mntone.AngelUmbrella.Controls.SettingsCard owner);
		}
	}

	namespace Navigation
	{

		[static_name("INavigationPropertiesStatics", 514F7EE7-3A01-51CD-AA81-C320C329FCDC)]
		static runtimeclass NavigationProperties
		{
			static void Initialize();

			static Windows.UI.Xaml.Interop.TypeName GetPageType(Microsoft.UI.Xaml.Controls.NavigationViewItem item);
			static void SetPageType(Microsoft.UI.Xaml.Controls.NavigationViewItem item, Windows.UI.Xaml.Interop.TypeName value);

			static Object GetParameter(Microsoft.UI.Xaml.Controls.NavigationViewItem item);
			static void SetParameter(Microsoft.UI.Xaml.Controls.NavigationViewItem item, Object value);

			static Microsoft.UI.Xaml.Media.Animation.NavigationTransitionInfo GetTransitionInfo(Microsoft.UI.Xaml.Controls.NavigationViewItem item);
			static void SetTransitionInfo(Microsoft.UI.Xaml.Controls.NavigationViewItem item, Microsoft.UI.Xaml.Media.Animation.NavigationTransitionInfo value);

			[noexcept] static Microsoft.UI.Xaml.DependencyProperty PageTypeProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty ParameterProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty TransitionInfoProperty { get; };
		}

	}

	namespace Triggers
	{

		[interface_name("IControlSizeTrigger", E82D709F-3699-4A90-998A-3243D97300F9)]
		[static_name("IControlSizeTriggerStatics", 79AE7071-EBAA-4F82-9EF5-5DC05945F7C1)]
		runtimeclass ControlSizeTrigger : Microsoft.UI.Xaml.StateTriggerBase
		{
			ControlSizeTrigger();

			Double MinWidth;
			Double MinHeight;
			Microsoft.UI.Xaml.FrameworkElement TargetElement;

			[noexcept] static Microsoft.UI.Xaml.DependencyProperty MinWidthProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty MinHeightProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty TargetElementProperty { get; };
		}

		[interface_name("IControlWidthTrigger", C5562E80-F6FF-4870-902C-2628222E8AF5)]
		[static_name("IControlWidthTriggerStatics", 9A821004-971E-445A-B6E5-8A92D032B537)]
		runtimeclass ControlWidthTrigger : Microsoft.UI.Xaml.StateTriggerBase
		{
			ControlWidthTrigger();

			Double MinWidth;
			Microsoft.UI.Xaml.FrameworkElement TargetElement;

			[noexcept] static Microsoft.UI.Xaml.DependencyProperty MinWidthProperty { get; };
			[noexcept] static Microsoft.UI.Xaml.DependencyProperty TargetElementProperty { get; };
		}

	}

}
