#pragma once

// Macro to convert the value of a variable to a string
#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)

#define VER_COPYRIGHT			ANGEL_COPYRIGHT
#define VER_COPYRIGHT_STR		STRINGIZE(ANGEL_COPYRIGHT)

#define VER_FILE_VERSION		ANGEL_VERSION_MAJOR, ANGEL_VERSION_MINOR, ANGEL_VERSION_BUILD, ANGEL_VERSION_REVISION
#define VER_FILE_VERSION_STR	STRINGIZE(ANGEL_VERSION_MAJOR)        \
								"." STRINGIZE(ANGEL_VERSION_MINOR)    \
								"." STRINGIZE(ANGEL_VERSION_BUILD)    \
								"." STRINGIZE(ANGEL_VERSION_REVISION)

#define VER_PRODUCT_VERSION		ANGEL_VERSION_MAJOR, ANGEL_VERSION_MINOR, ANGEL_VERSION_PATCH, ANGEL_VERSION_PREID
#ifdef ANGEL_VERSION_PRERELEASE
#define VER_PRODUCT_VERSION_STR	STRINGIZE(ANGEL_VERSION_MAJOR)        \
								"." STRINGIZE(ANGEL_VERSION_MINOR)    \
								"." STRINGIZE(ANGEL_VERSION_PATCH)    \
								"-" STRINGIZE(ANGEL_VERSION_PRERELEASE)
#else
#define VER_PRODUCT_VERSION_STR	STRINGIZE(ANGEL_VERSION_MAJOR)        \
								"." STRINGIZE(ANGEL_VERSION_MINOR)    \
								"." STRINGIZE(ANGEL_VERSION_PATCH)
#endif
