#pragma once

// Macro to convert the value of a variable to a string
#define STRINGIZE2(s) #s
#define STRINGIZE(s) STRINGIZE2(s)


#define VER_FILE_VERSION		ANGEL_VERSION_MAJOR, ANGEL_VERSION_MINOR, ANGEL_VERSION_BUILD, ANGEL_VERSION_REVISION
#define VER_FILE_VERSION_STR	STRINGIZE(ANGEL_VERSION_MAJOR)        \
								"." STRINGIZE(ANGEL_VERSION_MINOR)    \
								"." STRINGIZE(ANGEL_VERSION_BUILD)    \
								"." STRINGIZE(ANGEL_VERSION_REVISION) \

#define VER_PRODUCT_VERSION         VER_FILE_VERSION
#define VER_PRODUCT_VERSION_STR		VER_FILE_VERSION_STR
